import os
os.system('echo Checking for updates.\n')
os.system('sudo apt-get update > /dev/null')
os.system('echo Installing Required components..\n')
os.system('sudo apt-get install -y git vim curl python2 gcc python2-dev libsssl-dev zlib1g-dev libpcap-dev > /dev/null')
os.system('echo Setting python2 as python...\n')
os.system('ln -s /usr/bin/python2 /usr/bin/python')
os.system('echo Installing python2-pip....\n')
os.system('python2 ./get-pip.py')
os.system('pip install psycopg2-binary scapy==2.3.2')
os.system('echo Installing Pyrit.....\n')
os.ssytem('git clone https://github.com/JPaulMora/Pyrit.git')
os.ssytem('cd Pyrit')
os.system('./setup.py clean')
os.system('./setup.py build')
os.system('./setup.py install')
os.system('pyrit -h')