import os
os.system('echo Checking for updates.\n')
os.system('sudo apt-get update > /dev/null')
time.sleep(5)
os.system('echo Installing Required components..\n')
os.system('sudo apt-get install -y git vim curl python2 gcc python2-dev libssl-dev zlib1g-dev libpcap-dev')
time.sleep(5)
os.system('echo Setting python2 as python...\n')
os.system('ln -s /usr/bin/python2 /usr/bin/python')
os.system('echo Installing python2-pip....\n')
os.system('python2 ./get-pip.py')
time.sleep(5)
os.system('pip install psycopg2-binary scapy==2.3.2')
time.sleep(5)
os.system('echo Installing Pyrit.....\n')
os.system('git clone https://github.com/JPaulMora/Pyrit.git')
time.sleep(10)
os.system('cd Pyrit')
os.system('./setup.py clean')
os.system('./setup.py build')
time.sleep(5)
os.system('./setup.py install')
time.sleep(10)
os.system('pyrit -h')
